"""add dump and prep tables

Revision ID: ca2e1ab0dd2f
Revises: f5baf9392bd0
Create Date: 2026-03-28 18:07:19.585080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2e1ab0dd2f'
down_revision: Union[str, Sequence[str], None] = 'f5baf9392bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dump_user_id'), 'dump', ['user_id'], unique=False)
    op.create_table('prep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dump_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dump_id'], ['dump.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_dump_id'), 'prep', ['dump_id'], unique=False)
    op.create_index(op.f('ix_prep_user_id'), 'prep', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prep_user_id'), table_name='prep')
    op.drop_index(op.f('ix_prep_dump_id'), table_name='prep')
    op.drop_table('prep')
    op.drop_index(op.f('ix_dump_user_id'), table_name='dump')
    op.drop_table('dump')
    # ### end Alembic commands ###
